<?php

return [
    'enabled' => env('OVERSEER_ENABLED', true),
    'connection' => env('OVERSEER_CONNECTION', 'mysql'),
    'events' => [
        \Statamic\Events\AssetContainerCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\AssetContainerDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\AssetContainerSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\AssetDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\AssetReplaced::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\AssetReuploaded::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\AssetSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\AssetUploaded::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Illuminate\Auth\Events\Login::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Illuminate\Auth\Events\Logout::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Illuminate\Auth\Events\Failed::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Illuminate\Auth\Events\PasswordReset::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\BlueprintCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\BlueprintDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\BlueprintSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\CollectionCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\CollectionDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\CollectionSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\CollectionTreeDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\CollectionTreeSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\EntryCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\EntryDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\EntrySaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\FieldsetCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\FieldsetDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\FieldsetSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\FormCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\FormDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\FormSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\FormSubmitted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\GlobalSetCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\GlobalSetDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\GlobalSetSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\NavDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\NavSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\NavTreeDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\NavTreeSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\RoleDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\RoleSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\TaxonomyCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\TaxonomyDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\TaxonomySaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\TermCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\TermDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\TermSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\UserCreated::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\UserDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\UserSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\UserGroupDeleted::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
        \Statamic\Events\UserGroupSaved::class => \Cboxdk\StatamicOverseer\Listeners\GenericListener::class,
    ]
];